<?php
// $Id$

/**
 * Implementation of hook_init().
 */
function powerballad_init() {
  drupal_add_css(drupal_get_path('module', 'powerballad') . '/powerballad.css');
}

/**
 * Implementation of hook_menu().
 */
function powerballad_menu() {
  $items = array();

  $items['ballad'] = array(
    'title' => 'I can be your module (you can be my theme)',
    'description' => 'The Drupal power ballad.',
    'page callback' => 'powerballad_page',
    'file' => 'powerballad.inc',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'navigation',
  );

  return $items;
}

/**
 * Fetches the content of the power ballad page.
 *
 * This function loads the necessary aspects of the power ballad
 * and displays them on the power ballad page.
 *
 * @return
 *   The themed power ballad.
 */
function powerballad_page() {
  $ballad = array();
  powerballad_load_aspect(&$ballad, 'structure');
  powerballad_load_aspect(&$ballad, 'chords');
  powerballad_load_aspect(&$ballad, 'lyrics');
  //  powerballad_load_aspect(&$ballad, 'comments');

  $header = t('This song is available under GPL. Your participation is welcome at !project-page. (Can you be my theme?)', array('!project-page' => l('the project page', 'http://http://drupal.org/project/powerballad')));
  $footer = t('');

  return theme('ballad', array('ballad' => $ballad, 'header' => $header, 'footer' => $footer));
}


/**
 * Implementation of hook_theme().
 */
function powerballad_theme($existing, $type, $theme, $path) {
  return array(
    'ballad' => array(
      'variables' => array('ballad' => NULL, 'header' => NULL, 'footer' => NULL),
    ),
  );
}

/**
 * Default theme function for the Power ballad.
 *
 * This function takes the parts of the power ballad and renders it to
 * somewhat nice-looking HTML.
 *
 * @param $ballad
 *   The array containing the ballad.
 * @param $header
 *   Any header message, displayed above the ballad. Default is NULL.
 * @param $footer
 *   Any footer message, displayed below the ballad. Default is NULL.
 *
 * @return
 *   The themed power ballad.
 */
function theme_ballad($variables) {
  $ballad = $variables['ballad'];
  $header = $variables['header'];
  $footer = $variables['footer'];

  $output = '';

  if ($header) {
    $output .= '<p class="powerballad-header">' . $header . '</p>';
  }

  foreach ($ballad as $row) {
    if ($row['structure']) {
      $output .= '<h3 class="powerballad-section">' . $row['structure'] . '</h3>';
      if ($row['chords']) {
        $output .= '<p class="powerballad-chords">' . $row['chords'] . '</p>';
      }
    }
    if ($row['lyrics']) {
      $output .= '<span class="powerballad-lyrics">' . $row['lyrics'] . '<br /></span>';
    }
  }


  if ($footer) {
    $output .= '<p class="footer powerballad-footer">' . $footer . '</p>';
  }

  return $output;
}
